name: Publish GitHub Pages
on: [push, workflow_dispatch]
jobs:
  steps:
    build:
      steps:
        - uses: actions/jekyll-build-pages@v1.0.7
    deploy:
      needs: build
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1